name: Main CI

on:
  workflow_call:
    inputs:
      language: 
        required: true
        type: string
      package_manager:
        required: false
        type: string

jobs:
  nodejs_ci:
    if: ${{ inputs.language == 'nodejs' }}
    uses: ./.github/workflows/nodejs.yml@master
    with:
      package_manager: ${{ inputs.package_manager }}
  go_ci:
    if: ${{ inputs.language == 'go' }}
    uses: ./.github/workflows/go.yml@master    
  rust_ci: 
    if: ${{ inputs.language == 'rust' }}
    uses: ./.github/workflows/rust.yml@master
  python_ci:
    if: ${{ inputs.language == 'python' }}
    uses: ./.github/workflows/python.yml@master